target 'JobQueueDemo' do
  use_frameworks!

  pod 'JobQueue/Queue', :path => "../"
  pod 'JobQueue/Storage/InMemory', :path => "../"
  pod 'JobQueue/Storage/CoreData', :path => "../"
  pod 'ReactiveSwift'
end
