target 'JobQueueDemo' do
  use_frameworks!

  pod 'JobQueue/Queue', :path => "../"
  pod 'JobQueue/Storage/InMemory', :path => "../"
  pod 'JobQueue/Storage/CoreData', :path => "../"
  pod 'JobQueue/Storage/CouchbaseLite', :path => "../"

  pod 'ReactiveSwift'
  pod 'NanoID'
  pod 'CouchbaseLite-Swift'
end
